"""fixing relation

Revision ID: 0c60c7d58e46
Revises: 40a058e73903
Create Date: 2024-09-09 13:40:51.841271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c60c7d58e46'
down_revision = '40a058e73903'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faces_visitor_id_fkey', 'faces', type_='foreignkey')
    op.drop_constraint('faces_client_id_fkey', 'faces', type_='foreignkey')
    op.create_foreign_key(None, 'faces', 'visitors', ['visitor_id'], ['id'])
    op.create_foreign_key(None, 'faces', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_foreign_key('faces_client_id_fkey', 'faces', 'visitors', ['client_id'], ['id'])
    op.create_foreign_key('faces_visitor_id_fkey', 'faces', 'clients', ['visitor_id'], ['id'])
    # ### end Alembic commands ###
