"""Revision Daily Salary

Revision ID: 2344241eaac2
Revises: 042c4353e757
Create Date: 2024-11-14 10:28:05.626690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2344241eaac2'
down_revision = '042c4353e757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_salary', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('daily_salary', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'hours_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'standard_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'max_late',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'late_deduction',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'min_overtime',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'overtime_pay',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('daily_salary', 'hours_worked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_salary', sa.Column('hours_worked', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('daily_salary', 'overtime_pay',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'min_overtime',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'late_deduction',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'max_late',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'standard_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'hours_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_salary', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_salary', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
