"""fix: delete max_late, late_deduction_rate, min_overtime, overtime_rate, overtime_pay

Revision ID: 30ed1dd8af5e
Revises: 5c3bd04e7847
Create Date: 2024-12-02 13:42:02.380047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ed1dd8af5e'
down_revision = '5c3bd04e7847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_salary', 'max_late')
    op.drop_column('daily_salary', 'min_overtime')
    op.drop_column('daily_salary', 'overtime_rate')
    op.drop_column('daily_salary', 'late_deduction_rate')
    op.drop_column('employee_daily_salary', 'overtime_pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_daily_salary', sa.Column('overtime_pay', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('daily_salary', sa.Column('late_deduction_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_salary', sa.Column('overtime_rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_salary', sa.Column('min_overtime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_salary', sa.Column('max_late', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
