"""fixing column company at visitor table

Revision ID: 36b98f743095
Revises: a3c5586e06ce
Create Date: 2024-09-11 16:39:32.423306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b98f743095'
down_revision = 'a3c5586e06ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visitors_company_key', 'visitors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('visitors_company_key', 'visitors', ['company'])
    # ### end Alembic commands ###
