"""fixing relation

Revision ID: 3790df901ddd
Revises: 0c60c7d58e46
Create Date: 2024-09-09 13:43:12.924948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3790df901ddd'
down_revision = '0c60c7d58e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
