"""fix position, daily, employee_daily and monthly_salary

Revision ID: 3b1d3c6523b1
Revises: 2344241eaac2
Create Date: 2024-11-15 16:24:18.921238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1d3c6523b1'
down_revision = '2344241eaac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daily_salary_position_id_fkey', 'daily_salary', type_='foreignkey')
    op.drop_column('daily_salary', 'position_id')
    op.add_column('employee_daily_salary', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('employee_daily_salary', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('employee_monthly_salary', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_column('employee_monthly_salary', 'bonus')
    op.drop_column('employee_monthly_salary', 'tax')
    op.drop_column('employee_monthly_salary', 'bpjs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_monthly_salary', sa.Column('bpjs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee_monthly_salary', sa.Column('tax', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee_monthly_salary', sa.Column('bonus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('employee_monthly_salary', 'year')
    op.drop_column('employee_daily_salary', 'year')
    op.drop_column('employee_daily_salary', 'month')
    op.add_column('daily_salary', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('daily_salary_position_id_fkey', 'daily_salary', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###
