"""Create Table Client, Visitor, Face, Transaction, Attandance

Revision ID: 40a058e73903
Revises: 44f4d1dd4882
Create Date: 2024-09-06 16:43:25.177866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40a058e73903'
down_revision = '44f4d1dd4882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_name'), 'clients', ['client_name'], unique=True)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_nik'), 'visitors', ['nik'], unique=True)
    op.create_index(op.f('ix_visitors_username'), 'visitors', ['username'], unique=True)
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('Check_in', sa.DateTime(), nullable=True),
    sa.Column('Check_out', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('image_base64', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'born_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('born_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('transactions')
    op.drop_table('faces')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_visitors_username'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_nik'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_clients_client_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
