"""add revoked token table

Revision ID: 439a72f8335c
Revises: 4bf332e74822
Create Date: 2024-11-26 15:32:30.954106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439a72f8335c'
down_revision = '4bf332e74822'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
