"""fix: company start_time and end_time change typedata

Revision ID: 49ad929f38fc
Revises: cfb4c18971a5
Create Date: 2024-11-12 17:16:19.113744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ad929f38fc'
down_revision = 'cfb4c18971a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
