"""Change late_deduction to late_deduction_rate in daily_salary

Revision ID: 4bf332e74822
Revises: cd803f998432
Create Date: 2024-11-19 09:45:22.174073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf332e74822'
down_revision = 'cd803f998432'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_salary', sa.Column('late_deduction_rate', sa.Integer(), nullable=False))
    op.drop_column('daily_salary', 'late_deduction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_salary', sa.Column('late_deduction', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('daily_salary', 'late_deduction_rate')
    # ### end Alembic commands ###
