"""feat: add updated_by in employee_monthly_salary

Revision ID: 58c621c26bc0
Revises: 77204507062c
Create Date: 2024-12-04 15:54:53.101547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c621c26bc0'
down_revision = '77204507062c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_monthly_salary', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_monthly_salary', 'updated_by')
    # ### end Alembic commands ###
