"""feat: add max_late and min_overtime in company

Revision ID: 5c3bd04e7847
Revises: 439a72f8335c
Create Date: 2024-11-29 14:53:59.292191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3bd04e7847'
down_revision = '439a72f8335c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add max_late and min_overtime columns with a default value (e.g., 0)
    op.add_column('companies', sa.Column('max_late', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('min_overtime', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'min_overtime')
    op.drop_column('companies', 'max_late')
    # ### end Alembic commands ###
