"""delete min_overtime in company

Revision ID: 77204507062c
Revises: 30ed1dd8af5e
Create Date: 2024-12-04 10:10:52.565915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77204507062c'
down_revision = '30ed1dd8af5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'min_overtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('min_overtime', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
