"""update column address and full name

Revision ID: 7a2a77370602
Revises: c64298266313
Create Date: 2024-09-23 16:04:00.231820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2a77370602'
down_revision = 'c64298266313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('visitors', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'address')
    op.drop_column('visitors', 'full_name')
    # ### end Alembic commands ###
