"""Reset migrations

Revision ID: 8ed2ba2a6252
Revises: 
Create Date: 2025-02-03 11:27:15.733549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ed2ba2a6252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perf_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('req_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('req_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resp_status', sa.SmallInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_logo', sa.String(), nullable=True),
    sa.Column('founded_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('basecamp', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('total_players', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('kartu_keluarga', sa.String(), nullable=False),
    sa.Column('ktp', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_guardians_id'), 'guardians', ['id'], unique=False)
    op.create_table('officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('OWNER', 'CHAIRMAN', 'HEAD_COACH', 'ASSISTANT_COACH', 'FITNESS_COACH', 'GOALKEEPING_COACH', 'TACTICAL_ANALYST', 'TEAM_DOCTOR', 'YOUTH_COACH', 'TALENT_SCOUT', 'GENERAL_MANAGER', 'MARKETING_DIRECTOR', 'SOCIAL_MEDIA_MANAGER', 'EVENT_COORDINATOR', name='positionenum'), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_officials_id'), 'officials', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('main_position', sa.Enum('GOALKEEPER', 'CENTER_BACK', 'LEFT_BACK', 'RIGHT_BACK', 'LEFT_WING_BACK', 'RIGHT_WING_BACK', 'DEFENSIVE_MIDFIELDER', 'CENTRAL_MIDFIELDER', 'ATTACKING_MIDFIELDER', 'LEFT_WINGER', 'RIGHT_WINGER', 'LEFT_WING_FORWARD', 'RIGHT_WING_FORWARD', 'SHADOW_STRIKER', 'STRIKER', 'COMPLETE_FORWARD', name='positionenum'), nullable=False),
    sa.Column('second_position', sa.Enum('GOALKEEPER', 'CENTER_BACK', 'LEFT_BACK', 'RIGHT_BACK', 'LEFT_WING_BACK', 'RIGHT_WING_BACK', 'DEFENSIVE_MIDFIELDER', 'CENTRAL_MIDFIELDER', 'ATTACKING_MIDFIELDER', 'LEFT_WINGER', 'RIGHT_WINGER', 'LEFT_WING_FORWARD', 'RIGHT_WING_FORWARD', 'SHADOW_STRIKER', 'STRIKER', 'COMPLETE_FORWARD', name='positionenum'), nullable=False),
    sa.Column('third_position', sa.Enum('GOALKEEPER', 'CENTER_BACK', 'LEFT_BACK', 'RIGHT_BACK', 'LEFT_WING_BACK', 'RIGHT_WING_BACK', 'DEFENSIVE_MIDFIELDER', 'CENTRAL_MIDFIELDER', 'ATTACKING_MIDFIELDER', 'LEFT_WINGER', 'RIGHT_WINGER', 'LEFT_WING_FORWARD', 'RIGHT_WING_FORWARD', 'SHADOW_STRIKER', 'STRIKER', 'COMPLETE_FORWARD', name='positionenum'), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('NISN', sa.Integer(), nullable=True),
    sa.Column('dominant_foot', sa.Enum('LEFT', 'RIGHT', 'BOTH', name='dominantfootenum'), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('total_event', sa.Integer(), nullable=False),
    sa.Column('total_match', sa.Integer(), nullable=False),
    sa.Column('playing_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('guardian_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('relationship_guardian', sa.Enum('FATHER', 'MOTHER', 'BROTHER', 'SISTER', 'UNCLE', 'AUNT', 'GRANDFATHER', 'GRANDMOTHER', 'OTHER', name='guardianrelationshipenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', name='uq_guardian_player')
    )
    op.create_index(op.f('ix_guardian_players_id'), 'guardian_players', ['id'], unique=False)
    op.create_table('team_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('types', sa.Enum('APPLICATION', 'INVITATION', name='applicationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_applications_id'), 'team_applications', ['id'], unique=False)
    op.create_table('team_officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('OWNER', 'CHAIRMAN', 'HEAD_COACH', 'ASSISTANT_COACH', 'FITNESS_COACH', 'GOALKEEPING_COACH', 'TACTICAL_ANALYST', 'TEAM_DOCTOR', 'YOUTH_COACH', 'TALENT_SCOUT', 'GENERAL_MANAGER', 'MARKETING_DIRECTOR', 'SOCIAL_MEDIA_MANAGER', 'EVENT_COORDINATOR', name='positionenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_id'),
    sa.UniqueConstraint('official_id', name='uq_team_official')
    )
    op.create_index(op.f('ix_team_officials_id'), 'team_officials', ['id'], unique=False)
    op.create_table('team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTER', 'SUBSTITUTE', name='playerstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', name='uq_team_player')
    )
    op.create_index(op.f('ix_team_players_id'), 'team_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_players_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_team_officials_id'), table_name='team_officials')
    op.drop_table('team_officials')
    op.drop_index(op.f('ix_team_applications_id'), table_name='team_applications')
    op.drop_table('team_applications')
    op.drop_index(op.f('ix_guardian_players_id'), table_name='guardian_players')
    op.drop_table('guardian_players')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_officials_id'), table_name='officials')
    op.drop_table('officials')
    op.drop_index(op.f('ix_guardians_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('revoked_tokens')
    op.drop_table('perf_logs')
    # ### end Alembic commands ###
