"""fix: daily salary ref position

Revision ID: 93ad66758fd9
Revises: f92a17482f1d
Create Date: 2024-11-12 16:57:39.680044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ad66758fd9'
down_revision = 'f92a17482f1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
