"""fixing column at transaction table

Revision ID: a3c5586e06ce
Revises: be5f6676da92
Create Date: 2024-09-11 10:54:27.776009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c5586e06ce'
down_revision = 'be5f6676da92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_client_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_visitor_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'visitors', ['visitor_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_visitor_id_fkey', 'transactions', 'clients', ['visitor_id'], ['id'])
    op.create_foreign_key('transactions_client_id_fkey', 'transactions', 'visitors', ['client_id'], ['id'])
    # ### end Alembic commands ###
