"""Change overtime_pay, normal_salary, total_salary to Float in employee_daily_salary and monthly

Revision ID: a56f16f915ad
Revises: ac805312bdd2
Create Date: 2024-11-18 15:39:03.275224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56f16f915ad'
down_revision = 'ac805312bdd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ubah kolom hours_worked ke Float
    op.alter_column(
        'employee_daily_salary', 'hours_worked',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Float,
        nullable=False
    )

    # Ubah kolom overtime_pay ke Float
    op.alter_column(
        'employee_daily_salary', 'overtime_pay',
        existing_type=sa.INTEGER(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Float,
        nullable=True
    )

    # Ubah kolom normal_salary ke Float
    op.alter_column(
        'employee_daily_salary', 'normal_salary',
        existing_type=sa.INTEGER(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Float,
        nullable=False
    )

    # Ubah kolom total_salary ke Float
    op.alter_column(
        'employee_daily_salary', 'total_salary',
        existing_type=sa.INTEGER(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Float,
        nullable=False
    )

    # Ubah kolom normal_salary ke Float
    op.alter_column(
        'employee_monthly_salary', 'normal_salary',
        existing_type=sa.INTEGER(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Float,
        nullable=False
    )

    # Ubah kolom total_salary ke Float
    op.alter_column(
        'employee_monthly_salary', 'total_salary',
        existing_type=sa.INTEGER(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Float,
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_daily_salary', 'hours_worked',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
