"""add column born_date,email,company in visitors

Revision ID: be5f6676da92
Revises: 3790df901ddd
Create Date: 2024-09-10 10:58:44.019952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5f6676da92'
down_revision = '3790df901ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('born_date', sa.DateTime(), nullable=True))
    op.add_column('visitors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('visitors', sa.Column('company', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'visitors', ['email'])
    op.create_unique_constraint(None, 'visitors', ['company'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='unique')
    op.drop_constraint(None, 'visitors', type_='unique')
    op.drop_column('visitors', 'company')
    op.drop_column('visitors', 'email')
    op.drop_column('visitors', 'born_date')
    # ### end Alembic commands ###
