"""Change hours_worked, overtime_pay, normal_salary, total_salary to Numeric in employee_daily_salary and monthly

Revision ID: be727787ece3
Revises: d9fdbcdd9f39
Create Date: 2024-11-18 16:42:33.536807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be727787ece3'
down_revision = 'd9fdbcdd9f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column(
        'employee_daily_salary', 'hours_worked',
        existing_type=sa.Integer(),
        type_=sa.Numeric(10, 2),
        nullable=False
    )

    op.alter_column(
        'employee_daily_salary', 'late_deduction',
        existing_type=sa.Integer(),
        type_=sa.Numeric(10, 2),
        nullable=False
    )

    op.alter_column(
        'employee_daily_salary', 'overtime_pay',
        existing_type=sa.Float(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Numeric(10, 2),
        nullable=True
    )

    # Ubah kolom normal_salary ke Float
    op.alter_column(
        'employee_daily_salary', 'normal_salary',
        existing_type=sa.Float(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Numeric(10, 2),
        nullable=False
    )

    # Ubah kolom total_salary ke Float
    op.alter_column(
        'employee_daily_salary', 'total_salary',
        existing_type=sa.Float(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Numeric(10, 2),
        nullable=False
    )

    # Ubah kolom normal_salary ke Float
    op.alter_column(
        'employee_monthly_salary', 'normal_salary',
        existing_type=sa.Float(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Numeric(10, 2),
        nullable=False
    )

    op.alter_column(
        'employee_monthly_salary', 'total_salary',
        existing_type=sa.Float(),  # Ganti sesuai tipe saat ini di database
        type_=sa.Numeric(10, 2),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
