"""add url column at transaction

Revision ID: c64298266313
Revises: 36b98f743095
Create Date: 2024-09-12 16:59:47.904327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64298266313'
down_revision = '36b98f743095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'url')
    # ### end Alembic commands ###
