"""Change overtime_pay to overtime_rate in daily_salary

Revision ID: cd803f998432
Revises: be727787ece3
Create Date: 2024-11-19 09:31:40.726834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd803f998432'
down_revision = 'be727787ece3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_salary', sa.Column('overtime_rate', sa.Integer(), nullable=False))
    op.drop_column('daily_salary', 'overtime_pay')
    op.alter_column('employee_daily_salary', 'late_deduction',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_daily_salary', 'late_deduction',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('daily_salary', sa.Column('overtime_pay', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('daily_salary', 'overtime_rate')
    # ### end Alembic commands ###
